name: FlutterScaffold
description: flutter scaffold

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  # sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0-0
  load: ^1.0.0
  fluttertoast: ^8.0.6
  # pull_to_refresh: ^1.6.5
  pull_to_refresh: 1.6.4-nullsafety.0
  sqflite: ^2.0.0+4
  rxdart: ^0.26.0
  carousel_slider: ^4.0.0-nullsafety.0
  marquee: ^2.1.0
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  connectivity: ^3.0.3
  webview_flutter: ^2.1.1
  uuid: ^3.0.4
  qr_code_scanner: ^0.4.0
  # page_turn: ^1.0.1
  json_annotation: ^4.0.0
  date_format: ^2.0.2
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/robert-luoqing/flutter_datetime_picker
  intl: ^0.17.0
  image_picker: ^0.7.4
  multi_image_picker: ^4.8.0
  path_provider: ^2.0.1
  web_socket_channel: ^2.0.0
  # video_player: ^2.1.1
  adaptive_action_sheet: ^2.0.0
  flutter_platform_widgets: ^1.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # js: ^0.6.3
  flutter_web_plugins:
    sdk: flutter
  flutter_html: ^2.1.1
  http: ^0.13.3
  path: ^1.8.0
  flutter_advanced_segment: ^2.0.1+2
  bottom_picker: ^1.0.2
  image_cropper: ^1.4.1
  # https://tau.canardoux.xyz/readme.html
  flutter_sound: ^8.4.2
  cached_network_image: ^3.1.0
  flutter_native_splash: ^1.2.4
  url_launcher: ^6.0.12
  photo_view: ^0.13.0
  syncfusion_flutter_pdfviewer: ^19.3.44-beta
  percent_indicator: ^3.4.0
  flutter_slidable: ^0.6.0
  tween_image_widget: ^0.0.2
  permission_handler: ^6.0.1
  device_info_plus: ^3.1.1
  wakelock: ^0.5.6

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter pub run build_runner build
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  change_app_package_name: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/index.html
    - assets/images/
    - assets/icons/
    - assets/icons/sound/
    - fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Microsoft YaHei
      fonts:
        - asset: fonts/msyh.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
